application:
  no-auth-endpoints: "/auth/**"
  authentication:
    signing-key: 7bfa83f908ca8aa761cb0bf199213a0e5d67b0c74402d9f9eb2d90b49b879f8e
    jwt-expiration-time: 600
  card:
    number:
      length: 16
    expiry-period-years: 4
    encryption:
      key: 658d696ada91791a8e074017c50f6faa
      salt: 2c49619184a5e96a2152f1510a1b4bbd

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: /db/migration/db.changelog-master.yaml
    enabled: true

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false