application:
  no-auth-endpoints: "/swagger-ui/**,/swagger-resources/*,/v3/api-docs/**,/auth/**"
  authentication:
    enabled: true
    signing-key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
    jwt-expiration-time: 600
    refresh-token-expiration-in-hours: 12
  card:
    number:
      length: 16
    expiry-period-years: 4
    encryption:
      key: 98d05327033af07fbae4774fa1a45d1f
      salt: cd30997262cc4e49fe7597391e59a0c8

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: /db/migration/db.changelog-master.yaml
    enabled: true